name: Pull Request
run-name: Creating Pull Request
on:
    push:
        branches:
            - 'feature/**'

jobs:
    Pull-Request:
        runs-on: ubuntu-22.04
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 'Pull Request'
              uses: peter-evans/create-pull-request@v8
              with:
                  branch: main
